services:
  caddy:
    image: docker.io/caddy:latest
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./website:/srv
    depends_on:
      - app

  app:
    build: .
    ports:
      - "127.0.0.1:3000:3000" # Bind to localhost ONLY for security
    cap_add:
      - SYS_ADMIN # Required for filed's FUSE mount
    devices:
      - /dev/fuse:/dev/fuse # Required for filed's FUSE mount
    environment:
      - FILED_STATE_FILE=/db/filed.db # State configuration via env
    secrets:
      - source: msmtp_config
        target: /run/secrets/msmtp_config
    volumes:
      - logs:/logs

  mailpit:
    image: docker.io/axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"

secrets:
  msmtp_config:
    file: ./msmtprc
volumes:
  logs:
